const questions = [
  {
    title: "Câu 1",
    words: [
      "How",
      "saved",
      "important information",
      "your computer?",
      "is",
      "on",
    ],
    correctOrder: [
      "How",
      "is",
      "important information",
      "saved",
      "on",
      "your computer?",
    ],
  },
  {
    title: "Câu 2",
    words: [
      "Photos of",
      "free-time activities",
      "by",
      "every day",
      "shared",
      "Tom.",
      "on social media",
      "are",
    ],
    correctOrder: [
      "Photos of",
      "free-time activities",
      "are",
      "shared",
      "on social media",
      "every day",
      "by",
      "Tom.",
    ],
  },
  {
    title: "Câu 3",
    words: [
      "Do",
      "you",
      "follow",
      "any",
      "famous",
      "singers",
      "or",
      "actors",
      "on",
      "Instagram?",
    ],
    correctOrder: [
      "Do",
      "you",
      "follow",
      "any",
      "famous",
      "singers",
      "or",
      "actors",
      "on",
      "Instagram?",
    ],
  },
  {
    title: "Câu 4",
    words: [
      "after ten min",
      "battery power.",
      "The screen",
      "turned off",
      "to",
      "save",
      "is",
      "usually",
    ],
    correctOrder: [
      "The screen",
      "is",
      "usually",
      "turned off",
      "after ten min",
      "to",
      "save",
      "battery power.",
    ],
  },
  {
    title: "Câu 5",
    words: [
      "What",
      "for",
      "information",
      "search",
      "do",
      "tools",
      "use",
      "you",
    ],
    correctOrder: [
      "What",
      "tools",
      "do",
      "you",
      "use",
      "to",
      "search",
      "for",
      "information",
    ],
  },
  {
    title: "Câu 6",
    words: [
      "Spider- Man",
      "Filma",
      "by",
      "USA",
      "the",
      "WBID",
      "produced",
      "Columbia Pictures.",
    ],
    correctOrder: [
      "Spider-Man",
      "films",
      "were",
      "produced",
      "in",
      "the",
      "USA",
      "by",
      "Columbia Pictures.",
    ],
  },
  {
    title: "Câu 7",
    words: [
      "when",
      "was",
      "the power",
      "out.",
      "Serena",
      "romantic",
      "film went",
      "a watching",
    ],
    correctOrder: [
      "Serena",
      "was",
      "watching",
      "a",
      "romantic",
      "film",
      "when",
      "the power",
      "went",
      "out.",
    ],
  },
  {
    title: "Câu 8",
    words: [
      "to my report",
      "information",
      "enough",
      "don't have finish before Friday.",
    ],
    correctOrder: [
      "I",
      "don't",
      "have",
      "enough",
      "information",
      "to",
      "finish",
      "my",
      "report",
      "before",
      "Friday.",
    ],
  },
  {
    title: "Câu 9",
    words: [
      "/want",
      "finished?",
      "watch again",
      "did",
      "to",
      "What movie",
      "you",
      "as soon as",
      "it",
    ],
    correctOrder: [
      "What",
      "movie",
      "did",
      "you",
      "want",
      "to",
      "watch",
      "again",
      "as",
      "soon",
      "as",
      "it",
      "finished?",
    ],
  },
  {
    title: "Câu 10",
    words: [
      "Its content",
      "Children",
      "too violent",
      "that film",
      "shouldn't",
      "see",
      "is",
    ],
    correctOrder: [
      "Children",
      "shouldn't",
      "see",
      "that",
      "film",
      "because",
      "its",
      "content",
      "is",
      "too",
      "violent.",
    ],
  },
  {
    title: "Câu 11",
    words: [
      "the",
      "/first",
      "Was",
      "created",
      "in",
      "/1950s?",
      "video game",
      "the",
    ],
    correctOrder: [
      "Was",
      "the",
      "first",
      "video",
      "game",
      "created",
      "in",
      "the",
      "1950s?",
    ],
  },
  {
    title: "Câu 12",
    words: [
      "Used",
      "give",
      "important",
      "news",
      "the second",
      "during",
      "Radios",
      "to",
      "were",
      "World War.",
    ],
    correctOrder: [
      "Radios",
      "were",
      "used",
      "to",
      "give",
      "important",
      "news",
      "during",
      "the",
      "second",
      "World War.",
    ],
  },
  {
    title: "Câu 13",
    words: [
      "In the past,",
      "phones",
      "text messages.",
      "/for",
      "making",
      "were",
      "calls",
      "and",
      "sending",
      "simple",
      "used mainly",
    ],
    correctOrder: [
      "In",
      "the",
      "past,",
      "phones",
      "were",
      "mainly",
      "used",
      "for",
      "making",
      "calls",
      "and",
      "sending",
      "simple",
      "text",
      "messages.",
    ],
  },
  {
    title: "Câu 14",
    words: [
      "was",
      "It's light",
      "keyboard",
      "plastic,",
      "so",
      "and",
      "easy",
      "made of",
      "The",
      "to",
      "carry",
    ],
    correctOrder: [
      "The",
      "keyboard",
      "was",
      "made",
      "of",
      "plastic,",
      "so",
      "it's",
      "light",
      "and",
      "easy",
      "to",
      "carry.",
    ],
  },
  {
    title: "Câu 15",
    words: [
      "to play",
      "musical",
      "Idea",
      "Instrument",
      "to learn",
      "a good",
      "be",
      "or piano,/like guitar/It would",
    ],
    correctOrder: [
      "It",
      "would",
      "be",
      "a",
      "good",
      "idea",
      "to",
      "learn",
      "to",
      "play",
      "a",
      "musical",
      "instrument",
      "like",
      "guitar",
      "or",
      "piano.",
    ],
  },
  {
    title: "Câu 16",
    words: [
      "In",
      "play football",
      "at school",
      "when",
      "were",
      "We",
      "Sturients",
      "We",
      "at",
      "football ground",
    ],
    correctOrder: [
      "We'd",
      "play",
      "football",
      "in",
      "the",
      "football",
      "ground",
      "when",
      "we",
      "were",
      "students",
      "at",
      "school.",
    ],
  },
  {
    title: "Câu 17",
    words: [
      "Think",
      "Be",
      "It would",
      "Live",
      "Do you",
      "Korean concert",
      "great",
      "by Black Pick?",
    ],
    correctOrder: [
      "Do",
      "you",
      "think",
      "it",
      "would",
      "be",
      "great",
      "to",
      "attend",
      "a",
      "live",
      "Korean",
      "concert",
      "by",
      "Black Pink?",
    ],
  },
  {
    title: "Câu 18",
    words: [
      "Have",
      "to travel",
      "enough money",
      "we would",
      "competition",
      "If we",
      "to Thalland",
      "this sports",
    ],
    correctOrder: [
      "If",
      "we",
      "won",
      "this",
      "sports",
      "competition,",
      "we",
      "would",
      "have",
      "enough",
      "money",
      "to",
      "travel",
      "to",
      "Thailand.",
    ],
  },
  {
    title: "Câu 19",
    words: [
      "The",
      "afternoon.",
      "he felt",
      "at noon,",
      "often steep",
      "In",
      "My father",
      "really Tired",
    ],
    correctOrder: [
      "My",
      "father",
      "wouldn't",
      "often",
      "sleep",
      "at",
      "noon,",
      "so",
      "he",
      "felt",
      "really",
      "tired",
      "in",
      "the",
      "afternoon.",
    ],
  },
  {
    title: "Câu 20",
    words: [
      "sightseeing",
      "was",
      "goling",
      "yesterday.",
      "the city",
      "all day",
      "She",
      "in",
    ],
    correctOrder: [
      "She",
      "was",
      "going",
      "sightseeing",
      "in",
      "the",
      "city",
      "all",
      "day",
      "yesterday.",
    ],
  },
  {
    title: "Câu 21",
    words: [
      "they couldn’t",
      "but",
      "get tickets.",
      "went to",
      "the theatre,",
      "They",
    ],
    correctOrder: [
      "They",
      "went",
      "to",
      "the",
      "theatre,",
      "but",
      "they",
      "couldn't",
      "get",
      "tickets.",
    ],
  },
  {
    title: "Câu 22",
    words: [
      "were exploring",
      "and Sarah",
      "when",
      "got lost.",
      "John",
      "the island",
      "they suddenly",
    ],
    correctOrder: [
      "John",
      "and",
      "Sarah",
      "were",
      "exploring",
      "the",
      "island",
      "when",
      "they",
      "suddenly",
      "got",
      "lost.",
    ],
  },
  {
    title: "Câu 23",
    words: [
      "a great time",
      "while they",
      "to visit",
      "were there.",
      "The group",
      "was having",
      "Paris",
    ],
    correctOrder: [
      "The",
      "group",
      "was",
      "having",
      "a",
      "great",
      "time",
      "to",
      "visit",
      "Paris",
      "while",
      "they",
      "were",
      "there.",
    ],
  },
  {
    title: "Câu 24",
    words: [
      "The",
      "were really",
      "arrived at",
      "when they",
      "tourists",
      "tired",
      "the hotel.",
    ],
    correctOrder: [
      "The",
      "tourists",
      "were",
      "really",
      "tired",
      "when",
      "they",
      "arrived",
      "at",
      "the",
      "hotel.",
    ],
  },
  {
    title: "Câu 26",
    words: [
      "must",
      "fit",
      "and",
      "They",
      "them",
      "stay",
      "keep",
      "healthy",
      "judo",
    ],
    correctOrder: [
      "They",
      "must",
      "do",
      "judo",
      "to",
      "keep",
      "them",
      "fit",
      "and",
      "stay",
      "healthy.",
    ],
  },
  {
    title: "Câu 27",
    words: [
      "go",
      "it’s",
      "because",
      "too",
      "horse racing.",
      "for",
      "cannot",
      "She",
      "expensive",
      "for",
      "her",
    ],
    correctOrder: [
      "She",
      "cannot",
      "go",
      "horse",
      "racing",
      "because",
      "it's",
      "too",
      "expensive",
      "for",
      "her.",
    ],
  },
  {
    title: "Câu 28",
    words: [
      "play",
      "you",
      "could",
      "What",
      "sport",
      "you",
      "high",
      "school?",
      "when",
      "were",
      "at",
    ],
    correctOrder: [
      "What",
      "sport",
      "could",
      "you",
      "play",
      "when",
      "you",
      "were",
      "at",
      "high",
      "school?",
    ],
  },
  {
    title: "Câu 29",
    words: [
      "the",
      "sporting",
      "events?",
      "Why",
      "do",
      "we",
      "organize",
      "have",
      "to",
    ],
    correctOrder: [
      "Why",
      "do",
      "we",
      "have",
      "to",
      "organize",
      "the",
      "sporting",
      "events?",
    ],
  },
  {
    title: "Câu 30",
    words: ["YOU", "Tind", "munical", "play?", "Whal"],
    correctOrder: [
      "What",
      "kind",
      "of",
      "musical",
      "instrument",
      "can",
      "you",
      "play?",
    ],
  },
  {
    title: "Câu 31",
    words: [
      "yesterday.",
      "in",
      "the",
      "town",
      "the",
      "museum",
      "We",
      "visited",
    ],
    correctOrder: [
      "We",
      "visited",
      "the",
      "museum",
      "in",
      "the",
      "town",
      "yesterday.",
    ],
  },
  {
    title: "Câu 32",
    words: [
      "I",
      "every",
      "ten",
      "years",
      "a",
      "new",
      "passport",
      "changes.",
      "my",
      "face",
      "need",
      "to",
      "get",
      "because",
    ],
    correctOrder: [
      "I",
      "need",
      "to",
      "get",
      "a",
      "new",
      "passport",
      "every",
      "ten",
      "years",
      "because",
      "my",
      "face",
      "changes.",
    ],
  },
  {
    title: "Câu 33",
    words: [
      "the",
      "accident.",
      "Linda",
      "when",
      "she",
      "saw",
      "the",
      "guidebook",
      "was",
      "reading",
    ],
    correctOrder: [
      "Linda",
      "was",
      "reading",
      "the",
      "guidebook",
      "when",
      "she",
      "saw",
      "the",
      "accident.",
    ],
  },
  {
    title: "Câu 34",
    words: [
      "The",
      "across",
      "the",
      "mountains.",
      "to",
      "take",
      "Korean",
      "tourists",
      "hired",
      "a",
      "local",
      "guide",
      "them",
    ],
    correctOrder: [
      "The",
      "Korean",
      "tourists",
      "hired",
      "a",
      "local",
      "guide",
      "to",
      "take",
      "them",
      "across",
      "the",
      "mountains.",
    ],
  },
  {
    title: "Câu 35",
    words: [
      "were",
      "taking",
      "photos",
      "it",
      "started",
      "when",
      "to",
      "rain.",
      "They",
    ],
    correctOrder: [
      "They",
      "were",
      "taking",
      "photos",
      "when",
      "it",
      "started",
      "to",
      "rain.",
    ],
  },
  {
    title: "Câu 36",
    words: [
      "busy",
      "to",
      "was",
      "to",
      "him",
      "take",
      "too",
      "Pater’s",
      "mother",
      "the",
      "cinema.",
    ],
    correctOrder: [
      "Pater’s",
      "mother",
      "was",
      "too",
      "busy",
      "to",
      "take",
      "him",
      "to",
      "the",
      "cinema.",
    ],
  },
  {
    title: "Câu 37",
    words: [
      "country?",
      "of",
      "in",
      "What",
      "mean",
      "is",
      "the",
      "most",
      "popular",
      "your",
      "transport",
    ],
    correctOrder: [
      "What",
      "is",
      "the",
      "most",
      "popular",
      "mean",
      "of",
      "transport",
      "in",
      "your",
      "country?",
    ],
  },
  {
    title: "Câu 38",
    words: [
      "download",
      "fast",
      "the",
      "enough",
      "film.",
      "to",
      "The",
      "laptop",
      "isn’t",
    ],
    correctOrder: [
      "The",
      "laptop",
      "isn't",
      "fast",
      "enough",
      "to",
      "download",
      "the",
      "film.",
    ],
  },
  {
    title: "Câu 39",
    words: [
      "better",
      "Which",
      "do",
      "place",
      "is",
      "live?",
      "to",
      "you",
      "think",
    ],
    correctOrder: [
      "Which",
      "place",
      "do",
      "you",
      "think",
      "is",
      "better",
      "to",
      "live?",
    ],
  },
  {
    title: "Câu 40",
    words: [
      "bicycles",
      "every",
      "day.",
      "school",
      "often",
      "students",
      "ride",
      "Young",
      "to",
    ],
    correctOrder: [
      "Young",
      "students",
      "often",
      "ride",
      "bicycles",
      "to",
      "school",
      "every",
      "day.",
    ],
  },
  {
    title: "Câu 41",
    words: [
      "My",
      "computer.",
      "I",
      "some",
      "animals",
      "photographs",
      "like",
      "in",
      "taking",
      "to",
      "save",
    ],
    correctOrder: [
      "I",
      "like",
      "taking",
      "some",
      "photographs",
      "of",
      "animals",
      "to",
      "save",
      "in",
      "my",
      "computer.",
    ],
  },
  {
    title: "Câu 42",
    words: [
      "at",
      "sister",
      "playing",
      "My",
      "guitar.",
      "is",
      "good",
      "really",
      "the",
    ],
    correctOrder: [
      "My",
      "sister",
      "is",
      "really",
      "good",
      "at",
      "playing",
      "the",
      "guitar.",
    ],
  },
  {
    title: "Câu 43",
    words: [
      "Marre",
      "when",
      "her",
      "homework",
      "she",
      "got",
      "did",
      "from",
      "the",
      "zoo.",
      "home",
    ],
    correctOrder: [
      "Marre",
      "did",
      "her",
      "homework",
      "when",
      "she",
      "got",
      "home",
      "from",
      "the",
      "zoo.",
    ],
  },
  {
    title: "Câu 44",
    words: [
      "It",
      "for",
      "to",
      "London.",
      "to",
      "buses",
      "move",
      "is",
      "school",
      "difficult",
    ],
    correctOrder: [
      "It",
      "is",
      "difficult",
      "for",
      "school",
      "buses",
      "to",
      "move",
      "to",
      "London.",
    ],
  },
  {
    title: "Câu 45",
    words: [
      "to",
      "enjoy",
      "going",
      "on",
      "my",
      "the",
      "own.",
      "cinema",
      "I",
      "don’t",
    ],
    correctOrder: [
      "I",
      "don’t",
      "enjoy",
      "going",
      "to",
      "the",
      "cinema",
      "on",
      "my",
      "own.",
    ],
  },
];

let currentIndex = 0;
let selectedAnswers = [];

const choicesDiv = document.getElementById("choices");
const answerList = document.getElementById("answerList");
const result = document.getElementById("result");
const title = document.getElementById("questionTitle");

function loadQuestion() {
  const q = questions[currentIndex];
  title.textContent = q.title;
  choicesDiv.innerHTML = "";
  answerList.innerHTML = "";
  result.textContent = "";
  selectedAnswers = [];

  // Trộn ngẫu nhiên từ:
  const shuffled = [...q.words].sort(() => Math.random() - 0.5);

  shuffled.forEach((word) => {
    const btn = document.createElement("button");
    btn.textContent = word;
    btn.className = "choice";
    btn.onclick = () => selectWord(btn);
    choicesDiv.appendChild(btn);
  });
}

function selectWord(button) {
  const li = document.createElement("li");
  li.textContent = button.textContent;
  answerList.appendChild(li);
  selectedAnswers.push(button.textContent);
  button.disabled = true;
  button.style.opacity = 0.5;
}

function checkAnswer() {
  const correct = questions[currentIndex].correctOrder;

  if (selectedAnswers.length !== correct.length) {
    result.textContent = "⚠️ Bạn chưa chọn đủ từ.";
    return;
  }

  const isCorrect = selectedAnswers.every((word, i) => word === correct[i]);
  result.textContent = isCorrect ? "✅ Chính xác!" : "❌ Sai rồi.";
}

function nextQuestion() {
  currentIndex++;
  if (currentIndex >= questions.length) {
    result.textContent = "🎉 Bạn đã hoàn thành tất cả các câu!";
    choicesDiv.innerHTML = "";
    answerList.innerHTML = "";
    title.textContent = "Hoàn thành!";
    return;
  }
  loadQuestion();
}

window.onload = loadQuestion;
